language: ruby
cache: bundler
sudo: false
rvm:
  - 2.0
  - 2.1
  - 2.2
before_script:
  - wget https://github.com/cloudfoundry-incubator/spiff/releases/download/v1.0.7/spiff_linux_amd64.zip -O /tmp/spiff.zip
  - unzip /tmp/spiff.zip && mkdir bin && mv spiff bin && chmod +x bin/spiff
  - export PATH=$PATH:$PWD/bin
addons:
  code_climate:
    repo_token:
      secure: "AThBxjXIeNoH4i3r5aRxhrcxXOXqKPcQwkRnipFh9wtKYNcRJGfDp1QBn5/N2r3s8sX3FsWJmEat5uJVhibz5BV6/WZFISicyXjSXTqtAi9rmtneA+fb5G/SqcVZmcyhLoOoBxPW+z2aB8zJSX9KHvTv4GaCzD+iuzhbF1SslYk="

